FROM --platform=linux/%%BALENA_ARCH%% linuxserver/duplicati:latest

COPY entrypoint.sh /custom-entrypoint.sh
RUN chmod +x /custom-entrypoint.sh

# Keep linuxserver's entrypoint
ENTRYPOINT ["/init"]

# Run your script BEFORE starting Duplicati
CMD ["/custom-entrypoint.sh"]
