FROM --platform=linux/%%BALENA_ARCH%% nodered/node-red:latest

USER root

RUN npm install --unsafe-perm --no-update-notifier --no-fund --only=production \
    node-red-contrib-influxdb \
    node-red-node-serialport \
    node-red-dashboard

USER node-red
