FROM --platform=linux/%%BALENA_ARCH%% linuxserver/swag:latest

# Copy nginx proxy configuration files
COPY grafana.subdomain.conf /defaults/proxy-confs/
COPY influxdb.subdomain.conf /defaults/proxy-confs/
COPY jupyterlab.subdomain.conf /defaults/proxy-confs/
COPY nodered.subdomain.conf /defaults/proxy-confs/
COPY homeassistant.subdomain.conf /defaults/proxy-confs/
COPY duplicati.subdomain.conf /defaults/proxy-confs/
COPY portainer.subdomain.conf /defaults/proxy-confs/

# Expose ports
EXPOSE 80 443
