# make sure that your dns has a record set for yourdomain.com
# assuming this container is called "swag", edit your homeassistant container's config
# located at /config/configuration.yaml to look like:
# http:
#   use_x_forwarded_for: true
#   trusted_proxies:
#     - 172.18.0.0/16

location /homeassistant {
    return 301 $scheme://$host/homeassistant/;
}

location ^~ /homeassistant/ {
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app homeassistant;
    set $upstream_port 8123;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    
    rewrite /homeassistant(.*) $1 break;
}

location ^~ /homeassistant/api/websocket {
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app homeassistant;
    set $upstream_port 8123;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port/api/websocket;
}
